apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: nginx-sts-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-sts-leader-election-role
subjects:
- kind: ServiceAccount
  name: nginx-sts-controller-manager
  namespace: system
