# permissions for end users to view nginxsts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxsts-viewer-role
rules:
- apiGroups:
  - demo.consol.de
  resources:
  - nginxsts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.consol.de
  resources:
  - nginxsts/status
  verbs:
  - get
