apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: nginx-sts.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: This will deploy Nginx as a StatefuleSet. This is an example! Don't use it in production!
  displayName: Nginx-StatefulSet
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - example
  - nginx
  links:
  - name: Nginx Sts
    url: https://nginx-sts.domain
  maturity: alpha
  provider:
    name: ConSol Software GmbH
    url: https://www.consol.de/
  version: 0.0.0
