apiVersion: demo.consol.de/v1alpha1
kind: NginxSts
metadata:
  name: nginxsts-sample
spec:
  # Default values copied from <project_dir>/helm-charts/nginx-sts/values.yaml
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: 1.19.7-alpine
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080
    type: ClusterIP
  
  
