---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxsts.demo.consol.de
spec:
  group: demo.consol.de
  names:
    kind: NginxSts
    listKind: NginxStsList
    plural: nginxsts
    singular: nginxsts
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NginxSts is the Schema for the nginxsts API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of NginxSts
            type: object
            required:
              - replicaCount
            properties:
              image:
                description: Configuration of the used nginx image
                type: object
                properties:
                  pullPolicy:
                    description: 'Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images'
                    type: string
                    pattern: '^(Always|Never|IfNotPresent)$'
                  repository:
                    description: The alternative image repository that should be used.
                    type: string
                  tag:
                    description: The alternative image tag that should be used.
                    type: string
              replicaCount:
                description: The number of replicas of the nginx stateful set.
                type: integer
                default: 1
              resources:
                description: The resources for the nginx pod.
                type: object
                properties:
                  limits: 
                    description: 'Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  requests: 
                    description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
              service:
                description: Definition of the nginx service
                type: object
                properties:
                  port:
                    description: The port that will be used for the nginx container. The defined port number must be greater than 1024.
                    type: integer
                    minimum: 1024
                  type:
                    description: type determines how the Service is exposed. Defaults to ClusterIP. Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer
                    type: string
                    pattern: '^(ExternalName|ClusterIP|NodePort|LoadBalancer)$'
          status:
            description: Status defines the observed state of NginxSts
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
